# Generated by Django 5.1.2 on 2024-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/participante/', verbose_name='Foto do Evento'),
        ),
    ]
