# Generated by Django 5.1.2 on 2024-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_app', '0002_participante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cnpj_empresa',
            field=models.CharField(max_length=14, verbose_name='CNPJ Empresa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/participante/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nome_empresa',
            field=models.CharField(max_length=100, verbose_name='Nome Empresa'),
        ),
    ]
