# Generated by Django 5.1.2 on 2025-02-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_app', '0004_alter_participacao_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cred_app.evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participacao',
            name='participante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cred_app.participante'),
            preserve_default=False,
        ),
    ]
