# Generated by Django 5.1.2 on 2025-02-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_app', '0005_alter_participacao_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cnpj_empresa',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Empresa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Empresa'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
