# Generated by Django 5.1.2 on 2025-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_app', '0006_alter_participante_cnpj_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pagamento Realizado'),
        ),
    ]
