# Generated by Django 5.1.2 on 2025-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred_app', '0007_participante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Evento'),
        ),
    ]
